name: Detect Code Optimizations with DeepSeek

on:
  pull_request:
    branches:
      - main

jobs:
  optimization-check:
    runs-on: self-hosted  # IMPORTANT: Use a self-hosted runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Ollama
        run: |
          curl -sSL https://ollama.com/install.sh | bash

      # REMOVE the ollama pull step - it's done on the runner

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: Run DeepSeek to analyze code (only changed files)
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          CHANGED_FILES=$(echo "${{ steps.changed-files.outputs.all_changed_files }}" | tr '\n' ' ')
          ollama run deepseek-r1 --input "$CHANGED_FILES" --output deepseek-report.json # Corrected model name

      - name: Upload DeepSeek report as an artifact
        if: steps.changed-files.outputs.all_changed_files != ''
        uses: actions/upload-artifact@v3
        with:
          name: deepseek-report
          path: deepseek-report.json
          if-no-files-found: error

      - name: Comment on Pull Request with DeepSeek suggestions
        if: steps.changed-files.outputs.all_changed_files != ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          REPORT=$(cat deepseek-report.json)
          if [[ -s deepseek-report.json ]]; then
            BODY="Code review complete! Check the suggestions for optimizations in the attached report.\n\n"

            if command -v jq >/dev/null 2>&1; then
              PRETTY_REPORT=$(echo "$REPORT" | jq .)
              BODY+="\`\`\`json\n$PRETTY_REPORT\n\`\`\`"
            else
              BODY+="\`\`\`json\n$REPORT\n\`\`\`"
              echo "jq is not installed. Raw JSON report attached."
            fi

            curl -X POST \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Content-Type: application/json" \
              -d "{ \"body\": \"$BODY\" }" \
              "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          else
            echo "No optimizations suggestions found or report is empty."
          fi

      - name: Download DeepSeek report (for debugging)
        if: always() && steps.changed-files.outputs.all_changed_files != ''
        uses: actions/download-artifact@v3
        with:
          name: deepseek-report
          path: ./