name: Code Review with DeepSeek-Coder R1

on:
  pull_request:  # Or 'push' if you want it on all pushes, but PRs are recommended
    branches:
      - main  # Protect your main branch

jobs:
  code-review:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install torch transformers accelerate sentencepiece pylint flake8 mypy

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs
          git lfs install

      - name: Cache DeepSeek-Coder R1 Model
        id: cache-model
        uses: actions/cache@v3
        with:
          path: deepseek-r1
          key: deepseek-r1-model-v1
          restore-keys: |
            deepseek-r1-model-v1

      - name: Download DeepSeek-Coder R1 Model (Fallback to Hugging Face)
        if: steps.cache-model.outputs.cache-hit != 'true'
        run: |
          mkdir -p deepseek-r1
          cd deepseek-r1
          echo "Attempting to download model from Hugging Face..."
          git lfs install
          git clone https://huggingface.co/deepseek-ai/deepseek-coder-1.3b-base
          cd deepseek-coder-1.3b-base

      - name: Run Static Analysis
        run: |
          pylint --rcfile=.pylintrc --output-format=text *.py > pylint_results.txt
          flake8 *.py > flake8_results.txt
          mypy --ignore-missing-imports *.py > mypy_results.txt

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin
          git diff --name-only origin/main...$GITHUB_SHA > changed_files.txt

      - name: Run Code Review with DeepSeek-Coder
        id: deepseek-review
        run: |
          python code_review.py  # Execute the Python script
          cat review_output.txt # For debugging: See the review output in the logs

      - name: Post Code Review to Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const reviewOutput = fs.readFileSync('review_output.txt', 'utf8');
            github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              body: reviewOutput,
              event: 'APPROVE' # Or 'REQUEST_CHANGES' to block merging
            });

      - name: Post Code Review to Commit (Fallback if not PR)
        if: github.event_name != 'pull_request'
        run: |
          COMMIT_SHA=$GITHUB_SHA
          COMMENT="Code review complete! Check the output below for suggestions on optimizations.\n\n$(cat review_output.txt)"
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d "{\"body\": \"$COMMENT\"}" \
            https://api.github.com/repos/${{ github.repository }}/commits/$COMMIT_SHA/comments